from statistics import mode
from django.db import models
from viewflow.models import Process
import uuid

class OperacionProcess(Process):
    texto = models.CharField(max_length=150, blank=True, null=True)
    numero = models.BigIntegerField(default=0)
    folio = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    aprobado_middle = models.BooleanField(default=False)
    aprobado_back = models.BooleanField(default=False)
    aprobado_benito = models.BooleanField(default=False)
    ultima_mod = models.DateTimeField(auto_now=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    class Meta:
        permissions = [  # Explicitly specified, but also can be autogenerated by Viewflow
            ('can_start_operation', 'Can start operacion'),
            ('can_see_hidden_field', 'Can see a hidden field')
        ]