# Generated by Django 3.2.15 on 2022-08-11 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('texto', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.BigIntegerField(default=0)),
                ('folio', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('aprobado_middle', models.BooleanField(default=False)),
                ('aprobado_back', models.BooleanField(default=False)),
                ('aprobado_benito', models.BooleanField(default=False)),
                ('ultima_mod', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_start_operation', 'Can start operacion'), ('can_see_hidden_field', 'Can see a hidden field')],
            },
            bases=('viewflow.process',),
        ),
    ]
